// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI0aC_PRuaHYJARS00oPDBrmO-5hIrBgc',
    appId: '1:947422770477:web:c1f6ba33c3465328894fa4',
    messagingSenderId: '947422770477',
    projectId: 'evaluationproject-6abcc',
    authDomain: 'evaluationproject-6abcc.firebaseapp.com',
    storageBucket: 'evaluationproject-6abcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQeuGwEKbtIc5MK5DmVaZVon0jXcaN2dc',
    appId: '1:947422770477:android:b947c28b25179ddc894fa4',
    messagingSenderId: '947422770477',
    projectId: 'evaluationproject-6abcc',
    storageBucket: 'evaluationproject-6abcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT5ZKAOKXuqbC-jK_7oS_VE5-9rwVEmgw',
    appId: '1:947422770477:ios:c895b920a5aae0d6894fa4',
    messagingSenderId: '947422770477',
    projectId: 'evaluationproject-6abcc',
    storageBucket: 'evaluationproject-6abcc.appspot.com',
    iosBundleId: 'com.example.secondevaluation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT5ZKAOKXuqbC-jK_7oS_VE5-9rwVEmgw',
    appId: '1:947422770477:ios:3e727f93095c87ec894fa4',
    messagingSenderId: '947422770477',
    projectId: 'evaluationproject-6abcc',
    storageBucket: 'evaluationproject-6abcc.appspot.com',
    iosBundleId: 'com.example.secondevaluation.RunnerTests',
  );
}
